server:
  port: 8087
  address: 0.0.0.0

spring:
  application:
    name: my-spring-boot-app


# Autres configurations nécessaires
# Par exemple, si tu utilises une base de données
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/your_database
#     username: your_username
#     password: your_password